# Generated by Django 5.1 on 2026-03-18 11:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_number", models.IntegerField(unique=True)),
                ("level_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["level_number"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_name", models.CharField(max_length=255)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("amount", "Amount-Based"),
                            ("department", "Department-Based"),
                            ("combined", "Combined (Amount + Department)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Departments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_number", models.CharField(max_length=100, unique=True)),
                ("subject", models.CharField(max_length=500)),
                ("description", models.TextField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Application Initiated"),
                            ("submitted", "Submitted by End User"),
                            ("pending_operator", "Pending Operator Review"),
                            ("rejected_operator", "Rejected by Operator"),
                            ("revision_pending", "Revision Pending from End User"),
                            ("pending_mk_sabhya", "Pending MK Sabhya Approval"),
                            ("rejected_mk_sabhya", "Rejected by MK Sabhya"),
                            ("pending_mk_sant", "Pending MK Sant Approval"),
                            ("rejected_mk_sant", "Rejected by MK Sant"),
                            ("pending_p_rajipaswami", "Pending P.Rajipaswami Approval"),
                            ("rejected_p_rajipaswami", "Rejected by P.Rajipaswami"),
                            ("pending_hdh_guruji", "Pending HDH Guruji Approval"),
                            ("approved", "Approved by HDH Guruji"),
                            ("rejected", "Rejected"),
                        ],
                        default="initiated",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_forms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_approval_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="approval_core.approvallevel",
                    ),
                ),
                (
                    "applicable_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="approval_core.approvalrule",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="approval_core.department",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_type", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="approval_documents/%Y/%m/%d/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="approval_core.approvalform",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Approval Documents",
            },
        ),
        migrations.CreateModel(
            name="ApprovalComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_text", models.TextField()),
                ("is_visible_to_enduser", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "commented_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="approval_core.approvalform",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Approval Comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("revision_requested", "Revision Requested"),
                            ("delegated", "Delegated to 3rd Party"),
                            ("commented", "Comment Added"),
                        ],
                        max_length=50,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("delegation_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delegated_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delegated_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="approval_core.approvalform",
                    ),
                ),
                (
                    "approval_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="approval_core.approvallevel",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Approval Actions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="approvalrule",
            name="applicable_departments",
            field=models.ManyToManyField(blank=True, to="approval_core.department"),
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("submission", "Form Submission"),
                            ("approval", "Approval Notification"),
                            ("rejection", "Rejection Notification"),
                            ("revision", "Revision Request"),
                            ("delegation", "Delegation Notification"),
                        ],
                        max_length=50,
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=500)),
                ("message", models.TextField()),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="approval_core.approvalform",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Notification Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RuleApprovalSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence_order", models.IntegerField()),
                ("is_mandatory", models.BooleanField(default=True)),
                ("can_delegate", models.BooleanField(default=True)),
                ("auto_approve_if_conditions_met", models.BooleanField(default=False)),
                (
                    "approval_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="approval_core.approvallevel",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="approval_core.approvalrule",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence_order"],
                "unique_together": {("rule", "sequence_order")},
            },
        ),
        migrations.AddField(
            model_name="approvalrule",
            name="approval_levels",
            field=models.ManyToManyField(
                through="approval_core.RuleApprovalSequence",
                to="approval_core.approvallevel",
            ),
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("end_user", "End User"),
                            ("operator", "Operator"),
                            ("mk_sabhya", "MK Sabhya"),
                            ("mk_sant", "MK Sant"),
                            ("p_rajipaswami", "P.Rajipaswami"),
                            ("hdh_guruji", "HDH Guruji"),
                            ("third_party", "3rd Party Verifier"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="approval_core.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_role",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Roles",
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="approval_core.department",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Email Templates",
                "unique_together": {("department", "role", "email")},
            },
        ),
    ]
