# Generated by Django 5.1 on 2026-03-18 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval_core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalform",
            name="current_approver",
            field=models.ForeignKey(
                blank=True,
                help_text="Currently responsible person at this level",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="currently_approving_forms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ApprovalLevelUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as primary if multiple users for same level+department",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="approval_core.approvallevel",
                    ),
                ),
                (
                    "departments",
                    models.ManyToManyField(
                        help_text="Departments this user is responsible for",
                        to="approval_core.department",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_level_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Approval Level Users",
                "ordering": ["approval_level", "user"],
                "unique_together": {("user", "approval_level")},
            },
        ),
    ]
