# Generated by Django 5.1 on 2026-03-18 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval_core", "0002_approvalform_current_approver_approvalleveluser"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Center",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("pincode", models.CharField(blank=True, max_length=10, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Centers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmailNotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_name", models.CharField(max_length=100, unique=True)),
                ("subject", models.CharField(max_length=500)),
                ("body", models.TextField()),
                (
                    "approval_link_text",
                    models.CharField(default="Click here to approve", max_length=100),
                ),
                (
                    "context_model",
                    models.CharField(
                        choices=[
                            ("approval_form", "Approval Form"),
                            ("approval_request", "Approval Request"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("submit", "Form Submitted"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("revision_requested", "Revision Requested"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Email Notification Templates",
                "ordering": ["template_name"],
            },
        ),
        migrations.AddField(
            model_name="department",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="approvalform",
            name="current_approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="currently_approving_forms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="approvalleveluser",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="department",
            name="code",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "User Login"),
                            ("logout", "User Logout"),
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("form_submission", "Form Submission"),
                            ("approval", "Approval"),
                            ("rejection", "Rejection"),
                            ("email_sent", "Email Sent"),
                        ],
                        max_length=50,
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=100, null=True)),
                ("model_id", models.IntegerField(blank=True, null=True)),
                ("old_values", models.JSONField(blank=True, null=True)),
                ("new_values", models.JSONField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("ip_address", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="approvalform",
            name="center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="approval_core.center",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="department_assignments",
                to="approval_core.center",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="approval_core.country",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("country", "code")},
        ),
        migrations.CreateModel(
            name="PostMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("center", "Center Post"),
                            ("department", "Department Post"),
                        ],
                        max_length=20,
                    ),
                ),
                ("role_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Post Masters",
                "ordering": ["post_type", "role_name"],
                "unique_together": {("post_type", "role_name")},
            },
        ),
        migrations.CreateModel(
            name="PostEmailMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mapping_type",
                    models.CharField(
                        choices=[("center", "Center"), ("department", "Department")],
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "person_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_emails",
                        to="approval_core.center",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_emails",
                        to="approval_core.department",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_mappings",
                        to="approval_core.postmaster",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Post Email Mappings",
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="approval_core.country",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Zones",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="center",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="centers",
                to="approval_core.zone",
            ),
        ),
        migrations.DeleteModel(
            name="EmailTemplate",
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "-created_at"], name="approval_co_user_id_9213e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["model_name", "model_id"], name="approval_co_model_n_c431a5_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="department",
            name="email",
        ),
        migrations.AlterUniqueTogether(
            name="zone",
            unique_together={("country", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="center",
            unique_together={("zone", "code")},
        ),
    ]
