# Generated by Django 5.1 on 2026-03-18 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval_core", "0003_center_country_emailnotificationtemplate_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postmaster",
            options={
                "ordering": ["post_type", "role_name"],
                "verbose_name_plural": "Posts",
            },
        ),
        migrations.CreateModel(
            name="EmailMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mapping_type",
                    models.CharField(
                        choices=[("center", "Center"), ("department", "Department")],
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "person_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_mappings",
                        to="approval_core.center",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_mappings",
                        to="approval_core.department",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_mappings",
                        to="approval_core.postmaster",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Email Mappings",
                "ordering": ["email"],
            },
        ),
        migrations.DeleteModel(
            name="PostEmailMapping",
        ),
    ]
