# Generated by Django 5.1 on 2026-03-19 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval_core", "0004_alter_postmaster_options_emailmapping_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalform",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="approval_core.department",
            ),
        ),
    ]
