# Generated by Django 5.1 on 2026-03-29 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalform',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
