# Generated by Django 5.1 on 2026-04-02 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0007_approvalform_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalform',
            name='attachment',
        ),
    ]
