# Generated by Django 5.1 on 2026-04-02 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0008_remove_approvalform_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='approval_core.center'),
        ),
    ]
