# Generated by Django 5.1 on 2026-04-04 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0009_userrole_center'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalcomment',
            name='is_visible_to_enduser',
        ),
        migrations.AddField(
            model_name='approvalcomment',
            name='show_to_lower_levels',
            field=models.BooleanField(default=False, help_text='If checked, lower levels (including End User) can see this comment'),
        ),
        migrations.AddField(
            model_name='approvalcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='approvalcomment',
            name='commented_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
