# Generated by Django 5.1 on 2026-04-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0010_remove_approvalcomment_is_visible_to_enduser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalcomment',
            name='visible_to_levels',
            field=models.ManyToManyField(blank=True, help_text='Select specific approval levels that can see this comment', related_name='visible_comments', to='approval_core.approvallevel'),
        ),
        migrations.AlterField(
            model_name='approvalcomment',
            name='show_to_lower_levels',
            field=models.BooleanField(default=False, help_text='If checked, all lower levels (including End User) can see this comment'),
        ),
    ]
