# Generated by Django 5.1 on 2026-04-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0011_approvalcomment_visible_to_levels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalform',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('initiated', 'Application Initiated'), ('submitted', 'Submitted by End User'), ('pending_operator', 'Pending Operator Review'), ('rejected_operator', 'Rejected by Operator'), ('revision_pending', 'Revision Pending from End User'), ('pending_mk_sabhya', 'Pending MK Sabhya Approval'), ('rejected_mk_sabhya', 'Rejected by MK Sabhya'), ('pending_mk_sant', 'Pending MK Sant Approval'), ('rejected_mk_sant', 'Rejected by MK Sant'), ('pending_p_rajipaswami', 'Pending Dept. Mukhya Sant Approval'), ('rejected_p_rajipaswami', 'Rejected by Dept. Mukhya Sant'), ('pending_hdh_guruji', 'Pending HDH Guruji Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=50),
        ),
    ]
