# Generated by Django 5.1 on 2026-04-08 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0012_alter_approvalform_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the contact person', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone number with country code e.g. +919876543210', max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('preferred_channel', models.CharField(choices=[('email', 'Email Only'), ('sms', 'SMS Only'), ('both', 'Both')], default='both', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='e.g. Delegate for XYZ, Emergency contact', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_contacts', to='approval_core.approvalform')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification Contacts',
                'ordering': ['-created_at'],
            },
        ),
    ]
