# Generated by Django 5.1 on 2026-04-09 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0015_alter_userprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruleapprovalsequence',
            options={'ordering': ['sequence_order'], 'verbose_name': 'Rule Approval Sequence', 'verbose_name_plural': 'Rule Approval Sequences'},
        ),
        migrations.RemoveField(
            model_name='ruleapprovalsequence',
            name='can_delegate',
        ),
        migrations.AddField(
            model_name='ruleapprovalsequence',
            name='allow_delegation',
            field=models.BooleanField(default=False, help_text='Allow the approver at this level to delegate to 3rd Party Verifier'),
        ),
        migrations.AlterField(
            model_name='approvalaction',
            name='action_type',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_requested', 'Revision Requested'), ('delegated', 'Delegated to 3rd Party Verifier'), ('commented', 'Comment Added')], max_length=50),
        ),
        migrations.AlterField(
            model_name='approvalaction',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ruleapprovalsequence',
            name='auto_approve_if_conditions_met',
            field=models.BooleanField(default=False, help_text='Automatically approve if predefined conditions are met'),
        ),
        migrations.AlterField(
            model_name='ruleapprovalsequence',
            name='is_mandatory',
            field=models.BooleanField(default=True, help_text='Is this level mandatory in the approval process?'),
        ),
        migrations.AlterField(
            model_name='ruleapprovalsequence',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='approval_core.approvalrule'),
        ),
        migrations.AlterField(
            model_name='ruleapprovalsequence',
            name='sequence_order',
            field=models.PositiveIntegerField(help_text='Order of this approval level in the sequence (1, 2, 3...)'),
        ),
    ]
