# Generated by Django 5.1 on 2026-04-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0016_alter_ruleapprovalsequence_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalform',
            name='delegated_email',
            field=models.EmailField(blank=True, help_text='Email address when delegated to external person', max_length=254, null=True),
        ),
    ]
