# Generated by Django 5.1 on 2026-04-09 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0017_approvalform_delegated_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalform',
            name='delegated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalform',
            name='is_delegated',
            field=models.BooleanField(default=False),
        ),
    ]
