# Generated by Django 5.1 on 2026-04-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0018_approvalform_delegated_by_approvalform_is_delegated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailnotificationtemplate',
            options={'ordering': ['event_type'], 'verbose_name': 'Email Notification Template', 'verbose_name_plural': 'Email Notification Templates'},
        ),
        migrations.AlterField(
            model_name='emailnotificationtemplate',
            name='approval_link_text',
            field=models.CharField(default='Click here to view and approve the form', help_text='Text for the approval button/link', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailnotificationtemplate',
            name='body',
            field=models.TextField(help_text='Use Django template variables: {{ form.form_number }}, {{ form.subject }}, {{ form.amount }}, {{ login_url }}, {{ user.get_full_name }}, {{ remarks }}'),
        ),
        migrations.AlterField(
            model_name='emailnotificationtemplate',
            name='context_model',
            field=models.CharField(choices=[('approval_form', 'Approval Form')], default='approval_form', max_length=50),
        ),
        migrations.AlterField(
            model_name='emailnotificationtemplate',
            name='event_type',
            field=models.CharField(choices=[('form_submitted', 'Form Submitted'), ('pending_approval', 'Pending Approval (Next Level)'), ('final_approved', 'Final Approval Completed'), ('rejected', 'Form Rejected'), ('revision_requested', 'Revision Requested'), ('delegated', 'Form Delegated'), ('delegation_returned', 'Delegation Returned')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='emailnotificationtemplate',
            name='template_name',
            field=models.CharField(help_text="Internal name, e.g., 'Pending Approval Notification'", max_length=150, unique=True),
        ),
    ]
