# Generated by Django 5.1 on 2026-04-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0020_approvalform_delegated_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalform',
            name='guest_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
