# Generated by Django 5.1 on 2026-04-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0022_alter_emailnotificationtemplate_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotificationtemplate',
            name='event_type',
            field=models.CharField(choices=[('form_submitted', 'Form Submitted'), ('pending_approval', 'Pending Approval (Next Level)'), ('final_approved', 'Final Approval Completed'), ('rejected', 'Form Rejected'), ('revision_requested', 'Revision Requested'), ('delegated', 'Internal Delegation'), ('external_delegated', 'External Delegation'), ('delegation_returned', 'Delegation Returned'), ('external_delegation_reply', 'External Delegation Reply')], max_length=50, unique=True),
        ),
    ]
