# Generated by Django 5.1 on 2026-04-11 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0023_alter_emailnotificationtemplate_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleapprovalsequence',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_approval_sequences', to='approval_core.approvalrule'),
        ),
    ]
