# Generated by Django 5.1 on 2026-04-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0024_alter_ruleapprovalsequence_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalaction',
            name='notified_at',
            field=models.DateTimeField(blank=True, help_text='When notification/delegation email was sent to this level', null=True),
        ),
        migrations.AddField(
            model_name='approvallevel',
            name='show_time_taken',
            field=models.BooleanField(default=True, help_text="Allow approvers to see 'Time Taken' for this level and all previous levels"),
        ),
    ]
