# Generated by Django 5.1 on 2026-04-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0025_approvalaction_notified_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100, unique=True)),
                ('event_type', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Form Approved'), ('rejected', 'Form Rejected'), ('revision_requested', 'Revision Requested'), ('delegated', 'Form Delegated'), ('delegation_returned', 'Delegation Returned')], max_length=50)),
                ('message_text', models.CharField(help_text='SMS text (max 160 chars). Use {form_number}, {subject}, {amount}, {approver_name}, {remarks}', max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Template',
                'verbose_name_plural': 'SMS Templates',
            },
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='sms_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='sms_message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='sms_status',
            field=models.CharField(choices=[('not_sent', 'Not Sent'), ('sent', 'Sent'), ('failed', 'Failed')], default='not_sent', max_length=20),
        ),
    ]
