# Generated by Django 5.1 on 2026-04-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0026_smstemplate_notificationlog_sms_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstemplate',
            name='event_type',
            field=models.CharField(choices=[('form_submitted', 'Form Submitted'), ('pending_approval', 'Pending Approval (Next Level)'), ('final_approved', 'Final Approval Completed'), ('rejected', 'Form Rejected'), ('revision_requested', 'Revision Requested'), ('delegated', 'Internal Delegation'), ('delegation_returned', 'Delegation Returned')], max_length=50),
        ),
    ]
