# Generated by Django 5.1 on 2026-04-12 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0027_alter_smstemplate_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='smstemplate',
            name='approval_level',
            field=models.ForeignKey(blank=True, help_text='Leave blank for All Levels, or select specific level', null=True, on_delete=django.db.models.deletion.SET_NULL, to='approval_core.approvallevel'),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='event_type',
            field=models.CharField(choices=[('form_submitted', 'Form Submitted'), ('pending_approval', 'Pending Approval (Next Level)'), ('approved', 'Form Approved'), ('final_approved', 'Final Approval Completed'), ('rejected', 'Form Rejected'), ('revision_requested', 'Revision Requested'), ('delegated', 'Internal Delegation'), ('delegation_returned', 'Delegation Returned')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='smstemplate',
            unique_together={('event_type', 'approval_level')},
        ),
    ]
