# Generated by Django 5.1 on 2026-04-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0028_smstemplate_approval_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleapprovalsequence',
            name='can_delegate',
            field=models.BooleanField(default=False, verbose_name='Allow Delegation'),
        ),
    ]
