# Generated by Django 5.1 on 2026-04-15 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0029_ruleapprovalsequence_can_delegate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruleapprovalsequence',
            name='can_delegate',
        ),
    ]
