# Generated by Django 5.1 on 2026-04-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0030_remove_ruleapprovalsequence_can_delegate'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalform',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
