# Generated by Django 5.1 on 2026-04-18 20:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0033_alter_emailnotificationtemplate_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualExpenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_amount', models.DecimalField(decimal_places=2, help_text='Actual amount spent by Center/Department', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('remarks', models.TextField(blank=True, help_text='Notes or context about the actual spend', null=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenditure_entries', to=settings.AUTH_USER_MODEL)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actual_expenditure', to='approval_core.approvalform')),
            ],
            options={
                'verbose_name': 'Actual Expenditure',
                'verbose_name_plural': 'Actual Expenditures',
                'ordering': ['-entered_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_report', models.BooleanField(default=False, help_text='Allow this user to view the Center/Department Approval Report')),
                ('can_enter_actual_amount', models.BooleanField(default=False, help_text='Allow this user to fill in the Actual Amount Spent for approved forms')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restrict_to_centers', models.ManyToManyField(blank=True, help_text='Leave empty to allow all centers. Select specific centers to restrict.', to='approval_core.center')),
                ('restrict_to_departments', models.ManyToManyField(blank=True, help_text='Leave empty to allow all departments. Select specific to restrict.', to='approval_core.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_permission', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Permission',
                'verbose_name_plural': 'Report Permissions',
                'ordering': ['user__username'],
            },
        ),
    ]
