# Generated by Django 5.1 on 2026-04-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0034_actualexpenditure_reportpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalform',
            name='latest_approval_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
