# Generated by Django 5.1 on 2026-04-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0035_approvalform_latest_approval_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalcomment',
            name='is_lesser_approval',
            field=models.BooleanField(default=False, help_text='Mark this if comment is for lesser approved amount'),
        ),
    ]
