# Generated by Django 5.1 on 2026-04-23 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0036_approvalcomment_is_lesser_approval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvaldocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name_plural': 'Approval Documents'},
        ),
        migrations.AddField(
            model_name='approvaldocument',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvaldocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approvaldocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='approvaldocument',
            index=models.Index(fields=['is_verified'], name='approval_co_is_veri_4832d8_idx'),
        ),
    ]
