# Generated by Django 5.1 on 2026-04-25 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0037_alter_approvaldocument_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalform',
            name='selected_center',
            field=models.ForeignKey(blank=True, help_text='Center selected by department user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_selected_forms', to='approval_core.center'),
        ),
        migrations.AddField(
            model_name='department',
            name='requires_center_selection',
            field=models.BooleanField(default=False, help_text='If enabled, end users from this department must select a center while creating a form.'),
        ),
    ]
