# Generated by Django 5.1 on 2026-04-26 09:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0038_dept_center_selection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=10, unique=True)),
                ('currency_symbol', models.CharField(default='', max_length=10)),
                ('rate_to_inr', models.DecimalField(decimal_places=6, help_text='1 unit of this currency = X INR e.g. 1 USD = 83.50 INR', max_digits=20)),
                ('fetched_date', models.DateField(default=django.utils.timezone.now)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ['currency_code'],
            },
        ),
        migrations.AddField(
            model_name='approvalform',
            name='amount_inr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='INR equivalent of amount at time of submission', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='approvalform',
            name='approved_amount_local',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Approved amount converted to submitter's local currency using submission rate", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='approvalform',
            name='currency_code',
            field=models.CharField(default='INR', help_text='Currency used when form was submitted e.g. USD, GBP, INR', max_length=10),
        ),
        migrations.AddField(
            model_name='approvalform',
            name='currency_symbol',
            field=models.CharField(default='₹', help_text='Currency symbol at time of submission e.g. $, £, ₹', max_length=10),
        ),
        migrations.AddField(
            model_name='approvalform',
            name='exchange_rate_used',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate at submission: 1 local currency unit = X INR', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='currency_code',
            field=models.CharField(default='INR', help_text='ISO 4217 currency code e.g. USD, GBP, AED, INR', max_length=10),
        ),
        migrations.AddField(
            model_name='country',
            name='currency_symbol',
            field=models.CharField(default='₹', help_text='Currency symbol e.g. $, £, د.إ, ₹', max_length=10),
        ),
    ]
