# Generated by Django 5.1 on 2026-04-27 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0039_multi_currency_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrule',
            name='applicable_country',
            field=models.ForeignKey(blank=True, help_text='Optional. Set ONLY for country-specific rules. Leave blank to keep existing center/department rules unchanged.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_rules', to='approval_core.country'),
        ),
        migrations.AddField(
            model_name='approvalrule',
            name='chain_type',
            field=models.CharField(choices=[('standard', 'Standard (Center / Department based)'), ('country_independent', 'A — Country Independent (own chain only)'), ('country_first', 'B — Country First, then India Chain'), ('country_notify', 'C — India Chain, Country notified at end')], default='standard', help_text="Only used when 'Applicable Country' is set. A: Country has its own independent chain. B: Country operator first, then normal India chain. C: Normal India chain first, country coordinator notified at end.", max_length=30),
        ),
    ]
