# Generated by Django 5.1 on 2026-05-05 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0040_approval_rule_country_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualexpenditure',
            name='work_completion_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Completion of work in percentage (0–100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='reportpermission',
            name='can_enter_work_completion',
            field=models.BooleanField(default=False, help_text='Allow this user to enter the Work Completion % for approved forms'),
        ),
    ]
