# Generated by Django 5.1 on 2026-05-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0041_work_completion_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='accessible_centers',
            field=models.ManyToManyField(blank=True, related_name='prabhari_roles', to='approval_core.center'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='accessible_departments',
            field=models.ManyToManyField(blank=True, related_name='prabhari_roles', to='approval_core.department'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('prabhari', 'P. Prabhari Sant'), ('end_user', 'End User'), ('operator', 'Operator'), ('mk_sabhya', 'MK Sabhya'), ('mk_sant', 'MK Sant'), ('p_rajipaswami', 'P.Rajipaswami'), ('hdh_guruji', 'HDH Guruji'), ('third_party', '3rd Party Verifier')], max_length=50),
        ),
    ]
