# Generated by Django 5.1 on 2026-05-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0042_userrole_accessible_centers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('end_user', 'End User'), ('operator', 'Operator'), ('mk_sabhya', 'MK Sabhya'), ('mk_sant', 'MK Sant'), ('p_rajipaswami', 'P.Rajipaswami'), ('hdh_guruji', 'HDH Guruji'), ('third_party', '3rd Party Verifier')], max_length=50),
        ),
    ]
