# Generated by Django 5.1 on 2026-05-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0043_alter_userrole_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('end_user', 'End User'), ('operator', 'Operator'), ('mk_sabhya', 'MK Sabhya'), ('mk_sant', 'MK Sant'), ('p_rajipaswami', 'Dept. Sant'), ('hdh_guruji', 'HDH Guruji'), ('third_party', '3rd Party Verifier')], max_length=50),
        ),
    ]
