# Generated by Django 5.1 on 2026-05-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0044_alter_userrole_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='event_type',
            field=models.CharField(choices=[('form_submitted', 'Form Submitted'), ('pending_approval', 'Pending Approval (Next Level)'), ('approved', 'Form Approved'), ('final_approved', 'Final Approval Completed'), ('rejected', 'Form Rejected'), ('revision_requested', 'Revision Requested'), ('delegated', 'Internal Delegation'), ('delegation_returned', 'Delegation Returned'), ('otp_sent', 'Password Reset OTP')], max_length=50),
        ),
    ]
