# Generated by Django 5.1 on 2026-05-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0045_userrole_mobile_number_alter_smstemplate_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotificationtemplate',
            name='event_type',
            field=models.CharField(choices=[('form_submitted', 'Form Submitted'), ('pending_approval', 'Pending Approval (Next Level)'), ('final_approved', 'Final Approval Completed'), ('final_approved_amount_changed', 'Final Approval with Amount Change - To Submitter'), ('amount_changed_notify_approvers', 'Amount Changed Notification - To Previous Approvers'), ('rejected', 'Form Rejected'), ('revision_requested', 'Revision Requested'), ('delegated', 'Internal Delegation'), ('external_delegated', 'External Delegation'), ('delegation_returned', 'Delegation Returned'), ('external_delegation_reply', 'External Delegation Reply'), ('new_user_registered', 'New User Registered')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='event_type',
            field=models.CharField(choices=[('form_submitted', 'Form Submitted'), ('pending_approval', 'Pending Approval (Next Level)'), ('approved', 'Form Approved'), ('final_approved', 'Final Approval Completed'), ('rejected', 'Form Rejected'), ('revision_requested', 'Revision Requested'), ('delegated', 'Internal Delegation'), ('delegation_returned', 'Delegation Returned'), ('otp_sent', 'Password Reset OTP'), ('new_user_registered', 'New User Registered')], max_length=50),
        ),
    ]
