# Generated by Django 5.1 on 2026-05-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0047_alter_emailnotificationtemplate_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaldocument',
            name='is_mom_attached',
            field=models.BooleanField(default=False, verbose_name='MOM Attached?'),
        ),
        migrations.AddField(
            model_name='approvaldocument',
            name='is_other_docs_ok',
            field=models.BooleanField(default=False, verbose_name='Plan/Quotation/Other Docs OK?'),
        ),
        migrations.AddField(
            model_name='approvaldocument',
            name='is_prescribed_format',
            field=models.BooleanField(default=False, verbose_name='In Prescribed Format?'),
        ),
        migrations.AddField(
            model_name='approvaldocument',
            name='is_signature_ok',
            field=models.BooleanField(default=False, verbose_name='Signatures OK?'),
        ),
        migrations.AddField(
            model_name='approvaldocument',
            name='prabhari_sign_location',
            field=models.CharField(blank=True, choices=[('form', 'Approval Form 1st Page'), ('email', 'Email Attachment')], max_length=10, null=True, verbose_name='Prabhari Sign Location'),
        ),
    ]
