# Generated by Django 5.1 on 2026-05-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0048_approvaldocument_is_mom_attached_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalaction',
            name='action_type',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('resubmitted', 'Resubmitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_requested', 'Revision Requested'), ('delegated', 'Delegated to 3rd Party Verifier'), ('approved_by_external', '3rd Party Verified (External)'), ('approved_by_internal', '3rd Party Verified (Internal)'), ('rejected_by_external', '3rd Party Rejected (External)'), ('rejected_by_internal', '3rd Party Rejected (Internal)'), ('delegation_returned', 'Delegation Returned'), ('commented', 'Comment Added')], max_length=50),
        ),
        migrations.AlterField(
            model_name='emailnotificationtemplate',
            name='event_type',
            field=models.CharField(choices=[('form_submitted', 'Form Submitted'), ('pending_approval', 'Pending Approval (Next Level)'), ('final_approved', 'Final Approval Completed'), ('final_approved_amount_changed', 'Final Approval with Amount Change - To Submitter'), ('amount_changed_notify_approvers', 'Amount Changed Notification - To Previous Approvers'), ('rejected', 'Form Rejected'), ('revision_requested', 'Revision Requested'), ('delegated', 'Internal Delegation'), ('external_delegated', 'External Delegation'), ('delegation_returned', 'Delegation Returned'), ('approved_by_external', '3rd Party Verified (External)'), ('approved_by_internal', '3rd Party Verified (Internal)'), ('rejected_by_external', '3rd Party Rejected (External)'), ('rejected_by_internal', '3rd Party Rejected (Internal)'), ('delegation_returned', 'Delegation Returned'), ('external_delegation_reply', 'External Delegation Reply'), ('otp_sent', 'Password Reset OTP'), ('new_user_registered', 'New User Registered (To Admin)'), ('user_activated', 'User Account Activated (To User)')], max_length=50, unique=True),
        ),
    ]
