# Generated by Django 5.1 on 2026-05-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0049_alter_approvalaction_action_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationWorkflowConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(default='Default Registration Rules', help_text='Name of this configuration block', max_length=100)),
                ('is_direct_registration', models.BooleanField(default=False, help_text='If checked, registrations skip all leader verification and go directly to Admin Activation status.')),
                ('is_active', models.BooleanField(default=True, help_text='Only one configuration block should be active at a time.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_center_posts', models.ManyToManyField(blank=True, help_text='Select which Center Post Roles are authorized to verify center registrations (e.g., Center Sant Email ID).', limit_choices_to={'post_type': 'center'}, related_name='authorizing_center_configs', to='approval_core.postmaster')),
                ('authorized_department_posts', models.ManyToManyField(blank=True, help_text='Select which Department Post Roles are authorized to verify department registrations (e.g., Department Leader Sant Email ID).', limit_choices_to={'post_type': 'department'}, related_name='authorizing_dept_configs', to='approval_core.postmaster')),
            ],
            options={
                'verbose_name': 'Registration Workflow Config',
                'verbose_name_plural': 'Registration Workflow Configs',
            },
        ),
    ]
