# Generated by Django 5.1 on 2026-05-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0050_registrationworkflowconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='phone_code',
            field=models.CharField(blank=True, help_text='International telephone prefix code (e.g., 91, 94, 61)', max_length=10, null=True),
        ),
    ]
