# Generated by Django 5.1 on 2026-05-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0051_country_phone_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='currency_code',
            field=models.CharField(blank=True, help_text='ISO 4217 currency code e.g. USD, GBP, AED, INR', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='currency_symbol',
            field=models.CharField(blank=True, help_text='Currency symbol e.g. $, £, د.إ, ₹', max_length=10, null=True),
        ),
    ]
