# Generated by Django 5.1 on 2026-05-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0053_userworkspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotificationtemplate',
            name='event_type',
            field=models.CharField(choices=[('reg_leader_pending', 'REG-01: External User Pending Local Center Leader Review'), ('reg_admin_pending', 'REG-02: User Verified by Center Leader Awaiting Approval of Admin'), ('reg_user_activated', 'REG-03: User Account Activated successfully'), ('reg_user_declined', 'REG-04: User Account Registration Declined'), ('new_user_registered', 'REG-05: Internal New User Registered Awaiting Approval of Admin'), ('form_submitted', 'FRM-01: Form Successfully Submitted'), ('pending_approval', 'WKF-01: Pending Approval (Forwarded to Next Level)'), ('revision_requested', 'WKF-02: Revision/Resubmission Requested'), ('final_approved', 'WKF-03: Final Approval Completed'), ('final_approved_amount_changed', 'WKF-04: Final Approval with Amount Change (To Submitter)'), ('amount_changed_notify_approvers', 'WKF-05: Amount Changed Notification (To Previous Approvers)'), ('rejected', 'WKF-06: Form Permanently Rejected'), ('delegated', 'DLG-01: Internal Delegation to 3rd Party'), ('external_delegated', 'DLG-02: External Delegation to Guest Email'), ('approved_by_internal', 'DLG-03: 3rd Party Verified (Internal)'), ('approved_by_external', 'DLG-04: 3rd Party Verified (External)'), ('rejected_by_internal', 'DLG-05: 3rd Party Rejected (Internal)'), ('rejected_by_external', 'DLG-06: 3rd Party Rejected (External)'), ('delegation_returned', 'DLG-07: Delegation Formally Returned'), ('external_delegation_reply', 'DLG-08: External Delegation Reply Received'), ('otp_sent', 'SYS-01: Password Reset OTP Transmission')], max_length=50),
        ),
        migrations.AlterField(
            model_name='emailnotificationtemplate',
            name='template_name',
            field=models.CharField(help_text="Internal name, e.g., '[REG-01] Vasna Center Version'", max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='emailnotificationtemplate',
            unique_together={('template_name', 'event_type')},
        ),
    ]
