# Generated by Django 5.1 on 2026-05-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0055_alter_smstemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalform',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('initiated', 'Application Initiated'), ('submitted', 'Submitted by End User'), ('pending_operator', 'Pending Operator Review'), ('rejected_operator', 'Rejected by Operator'), ('revision_pending', 'Revision Pending from End User'), ('pending_mk_sabhya', 'Pending MK Sabhya Approval'), ('rejected_mk_sabhya', 'Rejected by MK Sabhya'), ('pending_mk_sant', 'Pending MK Sant 1 Approval'), ('rejected_mk_sant', 'Rejected by MK Sant 1'), ('pending_p_rajipaswami', 'Pending MK Sant 2 Approval'), ('rejected_p_rajipaswami', 'Rejected by MK Sant 2'), ('pending_hdh_guruji', 'Pending HDH Guruji Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('end_user', 'End User'), ('operator', 'Operator'), ('mk_sabhya', 'MK Sabhya'), ('mk_sant', 'MK Sant 1'), ('p_rajipaswami', 'MK Sant 2'), ('hdh_guruji', 'HDH Guruji'), ('third_party', '3rd Party Verifier')], max_length=50),
        ),
    ]
