# Generated by Django 5.1 on 2026-05-25 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0056_alter_approvalform_status_alter_userrole_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRestoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('backup_full', 'Full Project Backup'), ('backup_db', 'Database Only Backup'), ('restore_full', 'Full Project Restore'), ('restore_db', 'Database Only Restore')], max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('file_size_kb', models.DecimalField(blank=True, decimal_places=2, max_digits=12, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('user_count_verified', models.IntegerField(default=0)),
                ('form_count_verified', models.IntegerField(default=0)),
                ('log_summary', models.TextField(blank=True)),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
