# Generated by Django 5.1 on 2026-06-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0057_backuprestorelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppNotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(help_text="Internal descriptive name, e.g., '[WKF-01] Forwarded WhatsApp alert'", max_length=255, unique=True)),
                ('event_type', models.CharField(choices=[('reg_leader_pending', 'REG-01: External User Pending Local Center Leader Review'), ('reg_admin_pending', 'REG-02: User Verified by Center Leader Awaiting Approval of Admin'), ('reg_user_activated', 'REG-03: User Account Activated successfully'), ('reg_user_declined', 'REG-04: User Account Registration Declined'), ('new_user_registered', 'REG-05: Internal New User Registered Awaiting Approval of Admin'), ('form_submitted', 'FRM-01: Form Successfully Submitted'), ('pending_approval', 'WKF-01: Pending Approval (Forwarded to Next Level)'), ('revision_requested', 'WKF-02: Revision/Resubmission Requested'), ('final_approved', 'WKF-03: Final Approval Completed'), ('final_approved_amount_changed', 'WKF-04: Final Approval with Amount Change (To Submitter)'), ('amount_changed_notify_approvers', 'WKF-05: Amount Changed Notification (To Previous Approvers)'), ('rejected', 'WKF-06: Form Permanently Rejected')], max_length=50)),
                ('message_body', models.TextField(help_text='Use Django bracket placeholders: {form_number}, {subject}, {amount}, {approver_name}, {remarks}')),
                ('button_text', models.CharField(blank=True, help_text='Optional text for CTA template buttons', max_length=100, null=True)),
                ('button_url', models.CharField(blank=True, help_text='Optional URL route for interactive redirect cards', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Notification Template',
                'verbose_name_plural': 'WhatsApp Notification Templates',
                'ordering': ['event_type'],
                'unique_together': {('template_name', 'event_type')},
            },
        ),
    ]
