# Generated by Django 5.1 on 2026-06-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0058_whatsappnotificationtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRoutingMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('FRM-01', 'FRM-01: Form Successfully Submitted'), ('WKF-01', 'WKF-01: Pending Approval (Forwarded to Next Level)'), ('WKF-02', 'WKF-02: Revision/Resubmission Requested'), ('WKF-03', 'WKF-03: Final Approval Completed'), ('WKF-04', 'WKF-04: Final Approval with Amount Change (To Submitter)'), ('WKF-05', 'WKF-05: Amount Changed Notification (To Previous Approvers)'), ('WKF-06', 'WKF-06: Form Permanently Rejected'), ('DLG-01', 'DLG-01: Internal Delegation to 3rd Party'), ('DLG-02', 'DLG-02: External Delegation to Guest Email'), ('DLG-07', 'DLG-07: Delegation Formally Returned'), ('DLG-08', 'DLG-08: External Delegation Reply Received'), ('REG-01', 'REG-01: External User Pending Local Center Leader Review'), ('REG-02', 'REG-02: User Verified by Center Leader Awaiting Approval of Admin'), ('REG-03', 'REG-03: User Account Activated successfully'), ('REG-04', 'REG-04: User Account Registration Declined'), ('REG-05', 'REG-05: Internal New User Registered Awaiting Approval of Admin'), ('SYS-01', 'SYS-01: Password Reset OTP Transmission'), ('user_act', 'user_activated: User Account Activation - To User')], max_length=10, unique=True, verbose_name='System Event Type')),
                ('email_center_account', models.BooleanField(default=False, verbose_name='Email: Center Account Email ID')),
                ('email_center_main', models.BooleanField(default=False, verbose_name='Email: Center Email Id')),
                ('email_center_sant', models.BooleanField(default=False, verbose_name='Email: Center Sant Email ID')),
                ('email_prabhari_sant', models.BooleanField(default=False, verbose_name='Email: Prabhari Sant Email Id')),
                ('email_zonal_head', models.BooleanField(default=False, verbose_name='Email: Zonal Head')),
                ('email_dept_main', models.BooleanField(default=False, verbose_name='Email: Department Email ID')),
                ('email_dept_leader_sant', models.BooleanField(default=False, verbose_name='Email: Department Leader Sant Email ID')),
                ('email_dept_sant', models.BooleanField(default=False, verbose_name='Email: Department Sant Email ID')),
                ('email_hod', models.BooleanField(default=False, verbose_name='Email: HOD Email Id')),
                ('email_mk_haribhakt', models.BooleanField(default=False, verbose_name='Email: MK Haribhakt')),
                ('email_mk_sant', models.BooleanField(default=False, verbose_name='Email: MK Sant')),
                ('email_secretary', models.BooleanField(default=False, verbose_name='Email: Secretary Email ID')),
                ('wa_center_account', models.BooleanField(default=False, verbose_name='WA: Center Account Email ID')),
                ('wa_center_main', models.BooleanField(default=False, verbose_name='WA: Center Email Id')),
                ('wa_center_sant', models.BooleanField(default=False, verbose_name='WA: Center Sant Email ID')),
                ('wa_prabhari_sant', models.BooleanField(default=False, verbose_name='WA: Prabhari Sant Email Id')),
                ('wa_zonal_head', models.BooleanField(default=False, verbose_name='WA: Zonal Head')),
                ('wa_dept_main', models.BooleanField(default=False, verbose_name='WA: Department Email ID')),
                ('wa_dept_leader_sant', models.BooleanField(default=False, verbose_name='WA: Department Leader Sant Email ID')),
                ('wa_dept_sant', models.BooleanField(default=False, verbose_name='WA: Department Sant Email ID')),
                ('wa_hod', models.BooleanField(default=False, verbose_name='WA: HOD Email Id')),
                ('wa_mk_haribhakt', models.BooleanField(default=False, verbose_name='WA: MK Haribhakt')),
                ('wa_mk_sant', models.BooleanField(default=False, verbose_name='WA: MK Sant')),
                ('wa_secretary', models.BooleanField(default=False, verbose_name='WA: Secretary Email ID')),
            ],
            options={
                'verbose_name': 'Unified Notification Router',
                'verbose_name_plural': 'Unified Notification Router',
            },
        ),
    ]
