# Generated by Django 5.1 on 2026-06-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0059_notificationroutingmatrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmapping',
            name='phone_number',
            field=models.CharField(blank=True, help_text='WhatsApp phone number with country code for this post role (e.g., 919876543210)', max_length=15, null=True),
        ),
    ]
