# Generated by Django 5.1 on 2026-06-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0060_emailmapping_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationroutingmatrix',
            name='email_end_user',
            field=models.BooleanField(default=False, verbose_name='Email: End User (Submitter)'),
        ),
        migrations.AddField(
            model_name='notificationroutingmatrix',
            name='sms_center_account',
            field=models.BooleanField(default=False, verbose_name='SMS: Center Accountant'),
        ),
        migrations.AddField(
            model_name='notificationroutingmatrix',
            name='sms_center_main',
            field=models.BooleanField(default=False, verbose_name='SMS: Center'),
        ),
        migrations.AddField(
            model_name='notificationroutingmatrix',
            name='sms_center_sant',
            field=models.BooleanField(default=False, verbose_name='SMS: Center Sant'),
        ),
        migrations.AddField(
            model_name='notificationroutingmatrix',
            name='sms_dept_leader_sant',
            field=models.BooleanField(default=False, verbose_name='SMS: Dept Leader Sant'),
        ),
        migrations.AddField(
            model_name='notificationroutingmatrix',
            name='sms_dept_main',
            field=models.BooleanField(default=False, verbose_name='SMS: Deptartment'),
        ),
        migrations.AddField(
            model_name='notificationroutingmatrix',
            name='sms_dept_sant',
            field=models.BooleanField(default=False, verbose_name='SMS: Dept Sant'),
        ),
        migrations.AddField(
            model_name='notificationroutingmatrix',
            name='sms_end_user',
            field=models.BooleanField(default=False, verbose_name='SMS: End User (Submitter)'),
        ),
        migrations.AddField(
            model_name='notificationroutingmatrix',
            name='sms_hod',
            field=models.BooleanField(default=False, verbose_name='SMS: HOD'),
        ),
        migrations.AddField(
            model_name='notificationroutingmatrix',
            name='sms_mk_haribhakt',
            field=models.BooleanField(default=False, verbose_name='SMS: MK Haribhakt'),
        ),
        migrations.AddField(
            model_name='notificationroutingmatrix',
            name='sms_mk_sant',
            field=models.BooleanField(default=False, verbose_name='SMS: MK Sant'),
        ),
        migrations.AddField(
            model_name='notificationroutingmatrix',
            name='sms_prabhari_sant',
            field=models.BooleanField(default=False, verbose_name='SMS: Prabhari Sant'),
        ),
        migrations.AddField(
            model_name='notificationroutingmatrix',
            name='sms_secretary',
            field=models.BooleanField(default=False, verbose_name='SMS: Secretary'),
        ),
        migrations.AddField(
            model_name='notificationroutingmatrix',
            name='sms_zonal_head',
            field=models.BooleanField(default=False, verbose_name='SMS: Zonal Head'),
        ),
        migrations.AddField(
            model_name='notificationroutingmatrix',
            name='wa_end_user',
            field=models.BooleanField(default=False, verbose_name='WA: End User (Submitter)'),
        ),
        migrations.AlterField(
            model_name='notificationroutingmatrix',
            name='email_center_account',
            field=models.BooleanField(default=False, verbose_name='Email: Center Accountant'),
        ),
        migrations.AlterField(
            model_name='notificationroutingmatrix',
            name='email_center_main',
            field=models.BooleanField(default=False, verbose_name='Email: Center'),
        ),
        migrations.AlterField(
            model_name='notificationroutingmatrix',
            name='email_center_sant',
            field=models.BooleanField(default=False, verbose_name='Email: Center Sant'),
        ),
        migrations.AlterField(
            model_name='notificationroutingmatrix',
            name='email_dept_leader_sant',
            field=models.BooleanField(default=False, verbose_name='Email: Department Leader Sant'),
        ),
        migrations.AlterField(
            model_name='notificationroutingmatrix',
            name='email_dept_main',
            field=models.BooleanField(default=False, verbose_name='Email: Department'),
        ),
        migrations.AlterField(
            model_name='notificationroutingmatrix',
            name='email_dept_sant',
            field=models.BooleanField(default=False, verbose_name='Email: Department Sant'),
        ),
        migrations.AlterField(
            model_name='notificationroutingmatrix',
            name='email_hod',
            field=models.BooleanField(default=False, verbose_name='Email: HOD'),
        ),
        migrations.AlterField(
            model_name='notificationroutingmatrix',
            name='email_prabhari_sant',
            field=models.BooleanField(default=False, verbose_name='Email: Prabhari Sant'),
        ),
        migrations.AlterField(
            model_name='notificationroutingmatrix',
            name='email_secretary',
            field=models.BooleanField(default=False, verbose_name='Email: Secretary'),
        ),
        migrations.AlterField(
            model_name='notificationroutingmatrix',
            name='event_type',
            field=models.CharField(choices=[('FRM-01', 'FRM-01: Form Successfully Submitted'), ('WKF-01', 'WKF-01: Pending Approval (Forwarded to Next Level)'), ('WKF-02', 'WKF-02: Revision/Resubmission Requested'), ('WKF-03', 'WKF-03: Final Approval Completed'), ('WKF-04', 'WKF-04: Final Approval with Amount Change (To Submitter)'), ('WKF-05', 'WKF-05: Amount Changed Notification (To Previous Approvers)'), ('WKF-06', 'WKF-06: Form Permanently Rejected'), ('DLG-01', 'DLG-01: Internal Delegation to 3rd Party'), ('DLG-02', 'DLG-02: External Delegation to Guest Email'), ('DLG-03', 'DLG-03: 3rd Party Verified (Internal)'), ('DLG-04', 'DLG-04: 3rd Party Verified (External)'), ('DLG-05', 'DLG-05: 3rd Party Rejected (Internal)'), ('DLG-06', 'DLG-06: 3rd Party Rejected (External)'), ('DLG-07', 'DLG-07: Delegation Formally Returned'), ('DLG-08', 'DLG-08: External Delegation Reply Received'), ('REG-01', 'REG-01: External User Pending Local Center Leader Review'), ('REG-02', 'REG-02: User Verified by Center Leader Awaiting Approval of Admin'), ('REG-03', 'REG-03: User Account Activated successfully'), ('REG-04', 'REG-04: User Account Registration Declined'), ('REG-05', 'REG-05: Internal New User Registered Awaiting Approval of Admin'), ('SYS-01', 'SYS-01: Password Reset OTP Transmission'), ('user_act', 'user_activated: User Account Activation - To User')], max_length=10, unique=True, verbose_name='System Event Type'),
        ),
        migrations.AlterField(
            model_name='notificationroutingmatrix',
            name='wa_center_account',
            field=models.BooleanField(default=False, verbose_name='WA: Center Accountant'),
        ),
        migrations.AlterField(
            model_name='notificationroutingmatrix',
            name='wa_center_sant',
            field=models.BooleanField(default=False, verbose_name='WA: Center Sant'),
        ),
        migrations.AlterField(
            model_name='notificationroutingmatrix',
            name='wa_dept_leader_sant',
            field=models.BooleanField(default=False, verbose_name='WA: Department Leader Sant'),
        ),
        migrations.AlterField(
            model_name='notificationroutingmatrix',
            name='wa_dept_main',
            field=models.BooleanField(default=False, verbose_name='WA: Department'),
        ),
        migrations.AlterField(
            model_name='notificationroutingmatrix',
            name='wa_dept_sant',
            field=models.BooleanField(default=False, verbose_name='WA: Department Sant'),
        ),
        migrations.AlterField(
            model_name='notificationroutingmatrix',
            name='wa_hod',
            field=models.BooleanField(default=False, verbose_name='WA: HOD'),
        ),
        migrations.AlterField(
            model_name='notificationroutingmatrix',
            name='wa_prabhari_sant',
            field=models.BooleanField(default=False, verbose_name='WA: Prabhari Sant'),
        ),
        migrations.AlterField(
            model_name='notificationroutingmatrix',
            name='wa_secretary',
            field=models.BooleanField(default=False, verbose_name='WA: Secretary'),
        ),
    ]
