# Generated by Django 5.1 on 2026-06-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0061_notificationroutingmatrix_email_end_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationroutingmatrix',
            old_name='email_center_account',
            new_name='email_center_accountant',
        ),
        migrations.RenameField(
            model_name='notificationroutingmatrix',
            old_name='email_dept_main',
            new_name='email_department',
        ),
        migrations.RenameField(
            model_name='notificationroutingmatrix',
            old_name='sms_center_main',
            new_name='sms_center',
        ),
        migrations.RenameField(
            model_name='notificationroutingmatrix',
            old_name='sms_center_account',
            new_name='sms_center_accountant',
        ),
        migrations.RenameField(
            model_name='notificationroutingmatrix',
            old_name='wa_center_account',
            new_name='wa_center_accountant',
        ),
        migrations.RenameField(
            model_name='notificationroutingmatrix',
            old_name='wa_dept_main',
            new_name='wa_department',
        ),
        migrations.RemoveField(
            model_name='notificationroutingmatrix',
            name='email_center_main',
        ),
        migrations.RemoveField(
            model_name='notificationroutingmatrix',
            name='sms_dept_main',
        ),
        migrations.RemoveField(
            model_name='notificationroutingmatrix',
            name='wa_center_main',
        ),
        migrations.AddField(
            model_name='notificationroutingmatrix',
            name='email_center',
            field=models.BooleanField(default=False, verbose_name='Email: Center'),
        ),
        migrations.AddField(
            model_name='notificationroutingmatrix',
            name='sms_department',
            field=models.BooleanField(default=False, verbose_name='SMS: Department'),
        ),
        migrations.AddField(
            model_name='notificationroutingmatrix',
            name='wa_center',
            field=models.BooleanField(default=False, verbose_name='WA: Center'),
        ),
        migrations.AlterField(
            model_name='notificationroutingmatrix',
            name='email_dept_leader_sant',
            field=models.BooleanField(default=False, verbose_name='Email: Dept Leader Sant'),
        ),
        migrations.AlterField(
            model_name='notificationroutingmatrix',
            name='email_dept_sant',
            field=models.BooleanField(default=False, verbose_name='Email: Dept Sant'),
        ),
        migrations.AlterField(
            model_name='notificationroutingmatrix',
            name='wa_dept_leader_sant',
            field=models.BooleanField(default=False, verbose_name='WA: Dept Leader Sant'),
        ),
        migrations.AlterField(
            model_name='notificationroutingmatrix',
            name='wa_dept_sant',
            field=models.BooleanField(default=False, verbose_name='WA: Dept Sant'),
        ),
    ]
