# Generated by Django 5.1 on 2026-06-18 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0063_alter_whatsappnotificationtemplate_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='media_channel',
            field=models.CharField(choices=[('email', 'Email Message'), ('sms', 'Cellular SMS'), ('whatsapp', 'WhatsApp Notification')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent Successfully'), ('failed', 'Delivery Failed'), ('pending', 'Pending Queue')], default='sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('form_submitted', 'Form Successfully Submitted'), ('pending_approval', 'Pending Approval (Forwarded to Next Level)'), ('revision_requested', 'Revision/Resubmission Requested'), ('final_approved', 'Final Approval Completed'), ('final_approved_amount_changed', 'Final Approval with Amount Change'), ('amount_changed_notify_approvers', 'Amount Changed Notification to Approvers'), ('rejected', 'Form Permanently Rejected'), ('delegated', 'Internal Delegation to 3rd Party'), ('external_delegated', 'External Delegation to Guest Email'), ('approved_by_internal', '3rd Party Verified (Internal)'), ('approved_by_external', '3rd Party Verified (External)'), ('rejected_by_internal', '3rd Party Rejected (Internal)'), ('rejected_by_external', '3rd Party Rejected (External)'), ('delegation_returned', 'Delegation Formally Returned'), ('external_delegation_reply', 'External Delegation Reply Received'), ('reg_leader_pending', 'External User Pending Local Review'), ('reg_admin_pending', 'User Verified Awaiting Admin Activation'), ('reg_user_activated', 'User Account Activated'), ('reg_user_declined', 'User Account Registration Declined'), ('new_user_registered', 'Internal User Registered Awaiting Admin'), ('otp_sent', 'Password Reset OTP Transmission')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='sms_status',
            field=models.CharField(blank=True, default='not_sent', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='subject',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
