# Generated by Django 5.1 on 2026-06-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_core', '0064_notificationlog_media_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='message',
            field=models.TextField(help_text='Stores the fully compiled text message or email HTML content body'),
        ),
    ]
