# Generated by Django 5.1 on 2026-06-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approval_core', '0065_alter_notificationlog_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterZipSyncProxy',
            fields=[
            ],
            options={
                'verbose_name': '⚡ One-Click Master ZIP Sync Engine',
                'verbose_name_plural': '⚡ One-Click Master ZIP Sync Engine',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('approval_core.country',),
        ),
    ]
